### Pytorch Tensors

In [1]:
import torch
torch.__version__

'1.8.1'

In [2]:
a = torch.ones(3);a

tensor([1., 1., 1.])

In [3]:
a[1:3]

tensor([1., 1.])

In [4]:
float(a[1])

1.0

In [5]:
a[2]=2.0;a

tensor([1., 1., 2.])

In [6]:
x = torch.tensor([1.0,2.0,3.0,4.0])
x

tensor([1., 2., 3., 4.])

In [7]:
x = torch.tensor([[1.0,2.0],[4.0,5.0],[6.0,7.0]])
print(x.shape)
x

torch.Size([3, 2])


tensor([[1., 2.],
        [4., 5.],
        [6., 7.]])

In [8]:
x = torch.zeros(3,2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [9]:
x = torch.FloatTensor([[1.,2.,3.],[3.,4.,5.]])
x.shape

torch.Size([2, 3])

In [10]:
x[1,1]

tensor(4.)

In [11]:
x[0],x[0].shape

(tensor([1., 2., 3.]), torch.Size([3]))

In [12]:
x.storage()

 1.0
 2.0
 3.0
 3.0
 4.0
 5.0
[torch.FloatStorage of size 6]

In [13]:
x.storage()[2]

3.0

In [14]:
x.storage()[2] = 7.0
x

tensor([[1., 2., 7.],
        [3., 4., 5.]])

In [15]:
x = torch.tensor([[1.0, 4.0, 6.0], [2.0, 1.0, 4.0], [3.0, 5.0, 2.0]])
y = x[1]
print(y,y.size(),y.shape)
y.storage_offset()

tensor([2., 1., 4.]) torch.Size([3]) torch.Size([3])


3

In [16]:
x.storage()

 1.0
 4.0
 6.0
 2.0
 1.0
 4.0
 3.0
 5.0
 2.0
[torch.FloatStorage of size 9]

In [17]:
x.t()

tensor([[1., 2., 3.],
        [4., 1., 5.],
        [6., 4., 2.]])

In [18]:
id(x.storage()) == id(x.t().storage())

False

In [19]:
double_x = torch.ones(3, 2, dtype=torch.double)
short_x = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)

In [20]:
print(double_x)
short_x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)


tensor([[1, 2],
        [3, 4]], dtype=torch.int16)

In [21]:
short_x.dtype

torch.int16

In [22]:
a = x.numpy();a

array([[1., 4., 6.],
       [2., 1., 4.],
       [3., 5., 2.]], dtype=float32)

In [23]:
A = torch.from_numpy(a);A

tensor([[1., 4., 6.],
        [2., 1., 4.],
        [3., 5., 2.]])

In [24]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
print(img_t.size())
img_t

torch.Size([3, 5, 5])


tensor([[[-0.1324, -0.4661,  0.3324, -0.3144, -0.4439],
         [ 0.3103, -0.7748, -0.4677,  0.4433, -1.7258],
         [-0.8825, -1.2434, -0.0161, -0.0554, -0.8433],
         [-1.6653,  1.7683, -0.2852, -0.8688,  1.1528],
         [-2.0075, -0.4289, -1.8887,  1.4540, -0.3024]],

        [[ 1.2002,  0.6331,  0.2873, -1.4623, -0.0649],
         [-0.6350, -0.0378, -0.0675,  1.0678,  0.2412],
         [-0.7364, -0.0342, -0.9610, -0.5131,  1.4381],
         [-0.2664, -1.2117,  1.7166, -0.5336, -0.5122],
         [-1.1311, -0.8541,  0.3458,  0.2876,  0.5513]],

        [[ 0.6273, -0.4890, -1.3238, -0.5743, -0.1205],
         [-0.9408,  1.2988, -0.6783,  0.1647, -0.8877],
         [-0.4433,  0.2678, -0.6627, -0.2085,  1.6654],
         [-0.5321,  0.5445, -1.4328,  1.8924,  1.1992],
         [-1.8238,  0.9525,  1.8084,  0.0589, -1.1853]]])

In [25]:
img_t[:,0,0]

tensor([-0.1324,  1.2002,  0.6273])

In [26]:
img_t[:,1,:]

tensor([[ 0.3103, -0.7748, -0.4677,  0.4433, -1.7258],
        [-0.6350, -0.0378, -0.0675,  1.0678,  0.2412],
        [-0.9408,  1.2988, -0.6783,  0.1647, -0.8877]])

In [27]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[-0.1167,  0.8605,  1.3232, -0.8642, -1.5353],
          [ 0.7773, -1.8475,  1.1623,  0.2831, -0.7023],
          [ 1.8527,  0.9615,  0.1129, -0.9316, -0.2849],
          [ 0.8076,  0.1691, -0.7286,  0.4022,  0.0243],
          [ 0.8724, -1.1585,  0.1504, -0.1383,  1.0036]],

         [[-0.8024, -0.6974,  0.2161, -1.4337, -1.5783],
          [-0.5338, -0.1701, -0.6760,  0.4904,  2.5893],
          [-0.0635,  1.5506, -0.8918, -1.7860, -0.5738],
          [ 0.4489,  0.6791,  1.1077, -0.4326, -0.6355],
          [ 1.6827, -0.0051, -0.7156, -0.1901,  0.2129]],

         [[-0.0645,  0.0806, -0.5374,  0.1504, -1.5130],
          [-1.2123, -0.4437,  0.4495, -0.3092, -0.7270],
          [-0.4760, -1.8297, -0.4220, -1.4024, -2.0155],
          [ 1.3007,  0.4732, -0.2867, -0.7158,  1.0119],
          [-0.4388, -0.4502,  0.4666,  1.4089, -0.6717]]],


        [[[ 0.1683,  1.2397,  0.1754, -0.2747, -0.3367],
          [-0.8565, -1.0207,  0.3399, -0.7124,  0.5646],
          [-2.1699, -1.

In [28]:
print(img_t.shape)
print(img_t.mean(-3))
img_t.mean(dim=0)

torch.Size([3, 5, 5])
tensor([[ 5.6501e-01, -1.0737e-01, -2.3467e-01, -7.8367e-01, -2.0977e-01],
        [-4.2182e-01,  1.6204e-01, -4.0452e-01,  5.5861e-01, -7.9078e-01],
        [-6.8739e-01, -3.3658e-01, -5.4662e-01, -2.5898e-01,  7.5340e-01],
        [-8.2128e-01,  3.6703e-01, -4.7513e-04,  1.6335e-01,  6.1329e-01],
        [-1.6541e+00, -1.1015e-01,  8.8509e-02,  6.0014e-01, -3.1214e-01]])


tensor([[ 5.6501e-01, -1.0737e-01, -2.3467e-01, -7.8367e-01, -2.0977e-01],
        [-4.2182e-01,  1.6204e-01, -4.0452e-01,  5.5861e-01, -7.9078e-01],
        [-6.8739e-01, -3.3658e-01, -5.4662e-01, -2.5898e-01,  7.5340e-01],
        [-8.2128e-01,  3.6703e-01, -4.7513e-04,  1.6335e-01,  6.1329e-01],
        [-1.6541e+00, -1.1015e-01,  8.8509e-02,  6.0014e-01, -3.1214e-01]])

In [29]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

weights.shape,unsqueezed_weights.shape

(torch.Size([3]), torch.Size([3, 1, 1]))

In [30]:
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [31]:
print(img_t.shape,unsqueezed_weights.shape)
img_weights = (img_t * unsqueezed_weights)
img_weights.shape

torch.Size([3, 5, 5]) torch.Size([3, 1, 1])


torch.Size([3, 5, 5])

In [32]:
print(batch_t.shape,unsqueezed_weights.shape)
batch_weights = (batch_t * unsqueezed_weights) 
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3) 
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

torch.Size([2, 3, 5, 5]) torch.Size([3, 1, 1])


(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [33]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
print(points)
second_point

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])


tensor([10.,  3.])

$f(x) = x^3 -7x^2+11x,f^{'}(x) = 3x^2-14x+11$

In [34]:
def func(x):
    return (x**3 - 7*x**2 + 11*x)

def dfunc(x):
    return(3*x**2-14*x+11)

In [35]:
func(3),dfunc(3)

(-3, -4)

In [36]:
x = torch.tensor(3.0,requires_grad=True)
x

tensor(3., requires_grad=True)

In [37]:
y=func(x)

In [38]:
type(y)

torch.Tensor

In [39]:
y

tensor(-3., grad_fn=<AddBackward0>)

In [40]:
x

tensor(3., requires_grad=True)

In [41]:
y.backward()

In [42]:
x.grad

tensor(-4.)

In [43]:
y.backward()

RuntimeError: Trying to backward through the graph a second time, but the saved intermediate results have already been freed. Specify retain_graph=True when calling .backward() or autograd.grad() the first time.

In [ ]:
u=torch.tensor(2.0,requires_grad=True)
v=torch.tensor(2.0,requires_grad=True)

In [ ]:
def fn(u,v):
    return 3*u**2*v - 4*v**3
def dfndu(u,v):
    return v*(6*u)
def dfndv(u,v):
    return 3*u**2-12*v**2
fn(u,v),dfndu(u,v),dfndv(u,v)

In [ ]:
f=3*u**2*v - 4*v**3

In [ ]:
f

In [ ]:
f.backward(retain_graph=True)

In [ ]:
u.grad,v.grad

In [ ]:
f.backward()
u.grad,v.grad

In [ ]:
weights = torch.ones(4,requires_grad=True)
x = 3
for epoch in range(3):
    model_output = (weights*x).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

https://www.kdnuggets.com/2020/06/fundamentals-pytorch.html

https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html